"""The docs contract, enforced: no paragraph lives in two places, and each canonical doc says so.

`tests/test_docs_links.py` keeps links and anchors honest. These two checks keep knowledge from
being copied between files (a copy goes stale in one place) and keep every canonical document's
opening line saying what it is canonical for.
"""

from __future__ import annotations

import itertools
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIN_CHARS = 120  # shorter blocks are headings, one-liners and table rows, not paragraphs
NEAR_DUPLICATE = 0.5  # share of 6-word sequences two paragraphs have in common
# Generated or historical files repeat other docs by design and are not part of the contract.
EXEMPT = {"BENCHMARK_RESULTS.md"}


def contract_docs() -> list[Path]:
    names = ["README.md", "SECURITY.md", "CONTRIBUTING.md", "CLAUDE.md", "plugin/README.md"]
    docs = [ROOT / n for n in names] + sorted((ROOT / "docs").glob("*.md"))
    docs.append(ROOT / "evals" / "datasets" / "README.md")
    return [p for p in docs if p.exists() and p.name not in EXEMPT]


def paragraphs(text: str) -> list[str]:
    found = []
    for block in re.split(r"\n\s*\n", text):
        flat = re.sub(r"\s+", " ", block).strip()
        if len(flat) >= MIN_CHARS and "```" not in block and not flat.startswith(("|", "<", "-->")):
            found.append(flat)
    return found


def shingles(text: str, size: int = 6) -> set[str]:
    words = re.findall(r"\w+", text.lower())
    return {" ".join(words[i : i + size]) for i in range(max(len(words) - size + 1, 1))}


def duplicates(paths: list[Path]) -> list[str]:
    """One line per pair of paragraphs, in different files, that say (nearly) the same thing."""
    items = [(p, t, shingles(t)) for p in paths for t in paragraphs(p.read_text(encoding="utf-8"))]
    found = []
    for (p1, t1, s1), (p2, _, s2) in itertools.combinations(items, 2):
        if p1 == p2:
            continue
        overlap = len(s1 & s2) / max(min(len(s1), len(s2)), 1)
        if overlap >= NEAR_DUPLICATE:
            found.append(f"{p1.name} and {p2.name} ({overlap:.0%}): {t1[:70]}...")
    return found


# ------------------------------------------------------------------------------ duplicate text


PARAGRAPH = (
    "Retries use exponential backoff with full jitter and honour the Retry-After header, and a "
    "request that is not safe to repeat is never retried; the limits are set per provider."
)


def test_the_detector_finds_a_paragraph_copied_into_a_second_file(tmp_path: Path) -> None:
    a, b = tmp_path / "a.md", tmp_path / "b.md"
    a.write_text(f"# A\n\n{PARAGRAPH}\n")
    b.write_text(f"# B\n\nUnrelated opening text that is long enough to count as a paragraph on "
                 f"its own, about something else entirely.\n\n{PARAGRAPH}\n")
    assert len(duplicates([a, b])) == 1


def test_the_detector_finds_a_lightly_reworded_copy(tmp_path: Path) -> None:
    a, b = tmp_path / "a.md", tmp_path / "b.md"
    a.write_text(PARAGRAPH + "\n")
    b.write_text(PARAGRAPH.replace("exponential backoff", "exponential back-off") + " See above.\n")
    assert duplicates([a, b])


def test_the_detector_ignores_short_lines_code_and_the_same_file(tmp_path: Path) -> None:
    a, b = tmp_path / "a.md", tmp_path / "b.md"
    a.write_text("Short line.\n\n```\n" + PARAGRAPH + "\n```\n\n" + PARAGRAPH + "\n\n" + PARAGRAPH)
    b.write_text("Short line.\n\n```\n" + PARAGRAPH + "\n```\n")
    assert duplicates([a, b]) == []


def test_no_paragraph_lives_in_two_documents() -> None:
    found = duplicates(contract_docs())
    assert not found, "move the text to its canonical file and link to it:\n" + "\n".join(found)


# ---------------------------------------------------------------------- canonical headers

CANONICAL = [
    "docs/ARCHITECTURE.md",
    "docs/BENCHMARKING.md",
    "docs/CLAUDE_CODE_AB.md",
    "docs/CONFIGURATION.md",
    "docs/COSTS.md",
    "docs/INTEGRATIONS.md",
    "docs/BENCHMARK_RESULTS.md",
    "SECURITY.md",
    "CONTRIBUTING.md",
    "evals/datasets/README.md",
]


def test_every_canonical_document_opens_by_saying_what_it_is_canonical_for() -> None:
    for name in CANONICAL:
        opening = (ROOT / name).read_text(encoding="utf-8")[:900].lower()
        assert "canonical" in opening or "generated by" in opening, (
            f"{name}: say in its first lines what it is the canonical source for"
        )


def test_the_canonical_list_matches_the_docs_contract_table() -> None:
    table = (ROOT / "CONTRIBUTING.md").read_text(encoding="utf-8")
    for name in CANONICAL:
        assert Path(name).name in table or name in table, f"{name} is missing from the contract"
